### ISSUE TITLE
Curious Question

### ISSUE THREAD

**Issue by 0xRar** [byAyy/css-checkpoint-goMyCode#1]
## **Why is there a class attribute and an id attribute in the same tag ?**

```
- <section class="work" id="work">
- <section class="resume" id="resume">
- <section class="contact" id="contact">
```

**Comment by HeartBeat1608** [comment]
In case you didn't get it yet. Class attribute can be used for generalized styling and the same classes could be applied over to other elements as well throughout the document (conditions apply). The id attribute is for unique reference, usually for selective styling and Javascript reference. it is easier to find element by ID than finding one by class (there could be multiple references to that class but id's are always unique).
